// src/domain/entities/user.ts

/**
 * Represents a User entity in the domain.
 * This interface defines the core properties of a user, independent of the database.
 */
export interface User {
  id: string;
  name: string;
  email: string;
  authProvider?: string | null;
  createdAt: Date;
  lastLogin?: Date | null;
}

/**
 * Interface for creating a new User.
 * 'id' and timestamps are often generated by the system.
 */
export interface UserCreateData {
  id: string;
  name: string;
  email: string;
  authProvider?: string;
  lastLogin?: Date;
}

export type UserId = { userId: string };

export type WithUserId<TData> = TData & UserId;
