services:
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql-db-hairdresser
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: my_app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: my_secret_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-gui
    restart: always
    ports:
      - "8089:8080" # Access Adminer on your host at http://localhost:8080
    environment:
      ADMINER_DEFAULT_SERVER: db # This connects to the 'db' service in the same compose file
    depends_on:
      - db # Ensures 'db' starts before 'adminer'

  backend:
    build: ./
    container_name: node-api-hairdresser
    restart: always
    ports:
      - "3021:3021" # or whatever port your Node.js server runs on
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: my_secret_password
      DB_NAME: my_app_db
    depends_on:
      - db

  backend:
    build: ./
    container_name: node-api-hairdresser
    restart: always
    ports:
      - "3021:3021" # or whatever port your Node.js server runs on
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: my_secret_password
      DB_NAME: my_app_db
    depends_on:
      - db

volumes:
  db_data:
