FROM node:22-bullseye

WORKDIR /backend

COPY backend/package.json ./

RUN npm install

COPY backend/ .

# COPY backend/init.sh ./init.sh

# RUN chmod +x ./init.sh

# running init.sh file to make 
    # 1. grant priviledges to database 
    # 2. prisma migrate, 
    # 3. prisma generate
# RUN npx prisma db pull
# RUN npx prisma migrate dev --name baseline --create-only
RUN npx prisma generate

# Aplikovat migrace
RUN npx prisma migrate deploy

RUN npm run build

CMD ["npm", "run" ,"start"]