version: '3.8'

services:
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql-db-hairdresser
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: my_app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: my_secret_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
