name: Translation Extract & Insert

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/website

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run translation extract and insert
        run: npm run translate-extract-and-insert --file=index.html

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lonyo/index.html lonyo/assets/lang/index-cs.json
          git diff --quiet || git commit -m "Auto: Update translations for index.html"
          git push || echo "No changes to commit"
